### ISSUE TITLE
Bitcoin Cash

### ISSUE THREAD

**Issue by trymeouteh** [basicswap/basicswap#18]
Please add Bitcoin Cash.

**Comment by A60AB5450353F40E** [comment]
With the May '22 Bitcoin Cash upgrade, swaps using adaptor signatures and HTLCs are now possible. Bitcoin Cash doesn't have SegWit, so the problem of malleability must be solved in a other way: by using covenants to forward the locked BCH to the refund contract.

More information: https://bitcoincashresearch.org/t/monero-bch-atomic-swaps/545/14

Note that there's a 10.5 XMR bounty available to anyone who first implwments it: https://bounties.monero.social/posts/37/10-500m-bch-xmr-atomic-swaps

**Comment by nahuhh** [comment]
> With the May '22 Bitcoin Cash upgrade, swaps using adaptor signatures and HTLCs are now possible. Bitcoin Cash doesn't have SegWit, so the problem of malleability must be solved in another way: by using covenants to forward the locked BCH to the refund contract.
> 
> More information: https://bitcoincashresearch.org/t/monero-bch-atomic-swaps/545/14
> 
> Note that there's a 10.5 XMR bounty available to anyone who first implements it: https://bounties.monero.social/posts/37/10-500m-bch-xmr-atomic-swaps

Bumping as there as been progress on the above

**Comment by A60AB5450353F40E** [comment]
>Bumping as there as been progress on the above

some more info:

- Optimized BCH contract: https://bitcoincashresearch.org/t/monero-bch-atomic-swaps/545/41 (+ a variant for BTC/LTC swaps)

- PHCitizen made an implementation in Rust which was sufficient to claim the bounty: https://github.com/PHCitizen/bch-xmr-swap

- Pat raised funds to create a DEX, and he made some progress (js libs for DLeq): https://github.com/mainnet-pat/dleq-tools

**Comment by nahuhh** [comment]
BCH is done
