### ISSUE TITLE
install tecnovert/coincurve errors

### ISSUE THREAD

**Issue by devwarrior777** [basicswap/basicswap#21]
Following the docs to install basicswap (not using docker)
https://academy.particl.io/en/latest/basicswap-guides/basicswapguides_installation.html#install-without-docker

...the build errors installing coincurve at the `pip3 install`line:
```ev@dev-ThinkPad-T430:~/coincurve-test/coincurve$ pip3 install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/dev/coincurve-test/coincurve
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  ```
pyproject.toml maybe needs updating?
 .

**Comment by nahuhh** [comment]
@devwarrior777 this shouldn't be an issue on latest versions. Please reopen if you are still having issues
