### ISSUE TITLE
adding coins

### ISSUE THREAD

**Issue by realsetvin** [basicswap/basicswap#85]
what is the procedure (or interest level) in adding more coins?

**Comment by nahuhh** [comment]
Depends on your install method.

OS and method please? 
(docker, manual deployment, linux scripts, windows gui)

**Comment by milahu** [comment]
"adding coins" as in "enable more of the available coins"
or as in "add new available coins to basicswap"?

[readme#available-assets](https://github.com/basicswap/basicswap#available-assets)

> If you’d like to add a cryptocurrency to BasicSwap,
> refer to how other cryptocurrencies have been integrated to the DEX by following [this link](https://academy.particl.io/en/latest/basicswap-guides/basicswapguides_apply.html).

... but that link is not really helpful, and i still have to study the source code
to add a new `basicswap/interface/somecoin.py`

**Comment by nahuhh** [comment]
> "adding coins" as in "enable more of the available coins"
> see [Enable or Disable Coins](https://academy.particl.io/en/latest/basicswap-guides/basicswapguides_addremovecoins.html) and `basicswap/config.py`
> 
> or as in "add new available coins to basicswap"?
> see [readme#available-assets](https://github.com/basicswap/basicswap#available-assets)
> 
> > If you’d like to add a cryptocurrency to BasicSwap,
> > refer to how other cryptocurrencies have been integrated to the DEX by following [this link](https://academy.particl.io/en/latest/basicswap-guides/basicswapguides_apply.html).
> 
> ... but that link is not really helpful, and i still have to study the source code
> to add a new `basicswap/interface/somecoin.py`

see the `decred` and `wow` branches for recent integrations

**Comment by nahuhh** [comment]
closing, no resp from op.

@realsetvin  reopen if necessary
